name: "Unit Testing"

on: [push]

jobs:
    unit-testing:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '17'
            - name: Test with Maven
              run: mvn clean test
